apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fxt9d6yqw-python 
  janus-idp.io/tekton: fxt9d6yqw-python
  backstage.io/kubernetes-id: fxt9d6yqw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fxt9d6yqw-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml