apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fxt9d6yqw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fxt9d6yqw-python 
  name: fxt9d6yqw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fxt9d6yqw-python 
